const flashcards = [
    { character: "的", pinyin: "de", translation: "particule de détermination", audio: "audio/de.mp3" },
    { character: "我", pinyin: "wǒ", translation: "je, moi" },
    { character: "你", pinyin: "nǐ", translation: "tu, toi" },
    { character: "是", pinyin: "shì", translation: "être" },
    { character: "了", pinyin: "le", translation: "particule grammaticale" },
    { character: "不", pinyin: "bù", translation: "non, particule négative" },
    { character: "在", pinyin: "zài", translation: "se trouver, être quelque part" },
    { character: "他", pinyin: "tā", translation: "il, lui" },
    { character: "我们", pinyin: "wǒmen", translation: "nous" },
    { character: "好", pinyin: "hǎo", translation: "bien, bon" },
    { character: "有", pinyin: "yǒu", translation: "avoir, y avoir" },
    { character: "这", pinyin: "zhè", translation: "ceci" },
    { character: "会", pinyin: "huì", translation: "savoir, pouvoir faire" },
    { character: "吗", pinyin: "ma", translation: "particule interrogative" },
    { character: "什么", pinyin: "shénme", translation: "quoi ?" },
    { character: "说", pinyin: "shuō", translation: "parler" },
    { character: "她", pinyin: "tā", translation: "elle" },
    { character: "想", pinyin: "xiǎng", translation: "penser ; avoir envie de" },
    { character: "一", pinyin: "yī", translation: "un, 1" },
    { character: "很", pinyin: "hěn", translation: "très" },
    { character: "人", pinyin: "rén", translation: "homme, personne" },
    { character: "那", pinyin: "nà", translation: "cela" },
    { character: "来", pinyin: "lái", translation: "venir" },
    { character: "都", pinyin: "dōu", translation: "tout, tous" },
    { character: "个", pinyin: "ge", translation: "classificateur générique" },
    { character: "能", pinyin: "néng", translation: "pouvoir" },
    { character: "去", pinyin: "qù", translation: "aller" },
    { character: "和", pinyin: "hé", translation: "et" },
    { character: "做", pinyin: "zuò", translation: "faire" },
    { character: "上", pinyin: "shàng", translation: "monter ; précédent" },
    { character: "没有", pinyin: "méiyǒu", translation: "ne pas avoir" },
    { character: "看", pinyin: "kàn", translation: "regarder, voir" },
    { character: "怎么", pinyin: "zěnme", translation: "comment ?" },
    { character: "现在", pinyin: "xiànzài", translation: "maintenant" },
    { character: "点", pinyin: "diǎn", translation: "point, heure" },
    { character: "呢", pinyin: "ne", translation: "particule interrogative" },
    { character: "太", pinyin: "tài", translation: "trop, extrêmement" },
    { character: "里", pinyin: "lǐ", translation: "à l’intérieur" },
    { character: "听", pinyin: "tīng", translation: "écouter, entendre" },
    { character: "谁", pinyin: "shéi", translation: "qui ?" },
    { character: "多", pinyin: "duō", translation: "beaucoup" },
    { character: "时候", pinyin: "shíhou", translation: "moment" },
    { character: "下", pinyin: "xià", translation: "descendre ; suivant" },
    { character: "谢谢", pinyin: "xièxie", translation: "merci, remercier" },
    { character: "先生", pinyin: "xiānsheng", translation: "monsieur ; mari" },
    { character: "喜欢", pinyin: "xǐhuan", translation: "aimer, apprécier" },
    { character: "大", pinyin: "dà", translation: "grand" },
    { character: "东西", pinyin: "dōngxi", translation: "chose, objet" },
    { character: "小", pinyin: "xiǎo", translation: "petit" },
    { character: "叫", pinyin: "jiào", translation: "appeler" },
    { character: "爱", pinyin: "ài", translation: "aimer, amour" },
    { character: "年", pinyin: "nián", translation: "année" },
    { character: "请", pinyin: "qǐng", translation: "inviter, svp" },
    { character: "回", pinyin: "huí", translation: "revenir, retourner" },
    { character: "工作", pinyin: "gōngzuò", translation: "travailler, travail" },
    { character: "钱", pinyin: "qián", translation: "argent" },
    { character: "吃", pinyin: "chī", translation: "manger" },
    { character: "开", pinyin: "kāi", translation: "ouvrir, conduire" },
    { character: "家", pinyin: "jiā", translation: "maison, famille" },
    { character: "朋友", pinyin: "péngyou", translation: "ami" },
    { character: "妈妈", pinyin: "māma", translation: "maman" },
    { character: "今天", pinyin: "jīntiān", translation: "aujourd’hui" },
    { character: "几", pinyin: "jǐ", translation: "combien ?" },
    { character: "爸爸", pinyin: "bàba", translation: "papa" },
    { character: "些", pinyin: "xiē", translation: "quelques, plusieurs" },
    { character: "怎么样", pinyin: "zěnmeyàng", translation: "comment ça va ?" },
    { character: "对不起", pinyin: "duìbuqǐ", translation: "désolé, pardon" },
    { character: "住", pinyin: "zhù", translation: "habiter" },
    { character: "三", pinyin: "sān", translation: "trois, 3" },
    { character: "高兴", pinyin: "gāoxìng", translation: "content" },
    { character: "买", pinyin: "mǎi", translation: "acheter" },
    { character: "医生", pinyin: "yīshēng", translation: "docteur, médecin" },
    { character: "字", pinyin: "zì", translation: "caractère, lettre" },
    { character: "猫", pinyin: "māo", translation: "chat" },
    { character: "水", pinyin: "shuǐ", translation: "eau" },
    { character: "学习", pinyin: "xuéxí", translation: "étudier, apprendre" },
    { character: "中国", pinyin: "Zhōngguó", translation: "Chine" },
    { character: "北京", pinyin: "Běijīng", translation: "Pékin" },
    { character: "汉语", pinyin: "Hànyǔ", translation: "chinois (langue)" },
];
