const flashcards = [
    { character: "就", pinyin: "jiù", translation: "alors" },
    { character: "要", pinyin: "yào, yāo", translation: "vouloir" },
    { character: "知道", pinyin: "zhīdao", translation: "savoir, connaître" },
    { character: "吧", pinyin: "ba, bā", translation: "particule grammaticale" },
    { character: "到", pinyin: "dào", translation: "arriver" },
    { character: "对", pinyin: "duì", translation: "correct, juste" },
    { character: "也", pinyin: "yě", translation: "aussi, également" },
    { character: "还", pinyin: "hái, huán", translation: "encore" },
    { character: "让", pinyin: "ràng", translation: "laisser, faire faire" },
    { character: "给", pinyin: "gěi, jǐ", translation: "donner, à" },
    { character: "过", pinyin: "guò", translation: "indique une action passée" },
    { character: "得", pinyin: "dé, děi, de", translation: "particule d’appréciation" },
    { character: "真", pinyin: "zhēn", translation: "vraiment, vrai" },
    { character: "着", pinyin: "zhe, zháo, zhuó", translation: "particule résultative" },
    { character: "可以", pinyin: "kěyǐ", translation: "pouvoir, être autorisé à" },
    { character: "别", pinyin: "bié, biè", translation: "impératif négatif, autre" },
    { character: "走", pinyin: "zǒu", translation: "marcher" },
    { character: "告诉", pinyin: "gàosu", translation: "dire" },
    { character: "因为", pinyin: "yīnwèi", translation: "parce que" },
    { character: "再", pinyin: "zài", translation: "à nouveau, encore" },
    { character: "快", pinyin: "kuài", translation: "rapide, vite" },
    { character: "但是", pinyin: "dànshì", translation: "mais" },
    { character: "已经", pinyin: "yǐjing", translation: "déjà" },
    { character: "为什么", pinyin: "wèishénme", translation: "pourquoi" },
    { character: "觉得", pinyin: "juéde", translation: "ressentir, trouver" },
    { character: "它", pinyin: "tā", translation: "il, elle (neutre pour objets)" },
    { character: "从", pinyin: "cóng", translation: "depuis, suivre" },
    { character: "找", pinyin: "zhǎo", translation: "chercher" },
    { character: "最", pinyin: "zuì", translation: "le plus" },
    { character: "可能", pinyin: "kěnéng", translation: "peut-être, possibilité" },
    { character: "次", pinyin: "cì", translation: "fois, nombre, classificateur" },
    { character: "出", pinyin: "chū", translation: "sortir" },
    { character: "孩子", pinyin: "háizi", translation: "enfant" },
    { character: "所以", pinyin: "suǒyǐ", translation: "c’est pourquoi" },
    { character: "两", pinyin: "liǎng", translation: "deux" },
    { character: "错", pinyin: "cuò", translation: "faute, faux, erreur" },
    { character: "等", pinyin: "děng", translation: "attendre" },
    { character: "问", pinyin: "wèn", translation: "demander, interroger" },
    { character: "问题", pinyin: "wèntí", translation: "question, problème" },
    { character: "一起", pinyin: "yìqǐ", translation: "ensemble" },
    { character: "开始", pinyin: "kāishǐ", translation: "commencer" },
    { character: "时间", pinyin: "shíjiān", translation: "temps, durée" },
    { character: "事情", pinyin: "shìqing", translation: "chose, affaire" },
    { character: "非常", pinyin: "fēicháng", translation: "très, extrêmement" },
    { character: "希望", pinyin: "xīwàng", translation: "espérer, souhaiter" },
    { character: "准备", pinyin: "zhǔnbèi", translation: "préparer" },
    { character: "比", pinyin: "bǐ", translation: "comparer, plus que" },
    { character: "意思", pinyin: "yìsi", translation: "sens, signification" },
    { character: "第一", pinyin: "dìyī", translation: "premier" },
    { character: "进", pinyin: "jìn", translation: "entrer, avancer" },
    { character: "大家", pinyin: "dàjiā", translation: "tout le monde" },
    { character: "新", pinyin: "xīn", translation: "nouveau" },
    { character: "您", pinyin: "nín", translation: "vous (de politesse)" },
    { character: "穿", pinyin: "chuān", translation: "porter, mettre des vêtements" },
    { character: "送", pinyin: "sòng", translation: "offrir, envoyer" },
    { character: "玩", pinyin: "wán", translation: "jouer, s’amuser" },
    { character: "长", pinyin: "cháng, zhǎng", translation: "long" },
    { character: "小时", pinyin: "xiǎoshí", translation: "heure (durée)" },
    { character: "完", pinyin: "wán", translation: "finir" },
    { character: "每", pinyin: "měi", translation: "chaque" },
    { character: "公司", pinyin: "gōngsī", translation: "entreprise, compagnie" },
    { character: "帮助", pinyin: "bāngzhù", translation: "aider" },
    { character: "晚上", pinyin: "wǎnshang", translation: "soirée, soir" },
    { character: "说话", pinyin: "shuōhuà", translation: "parler, dire" },
    { character: "门", pinyin: "mén", translation: "porte" },
    { character: "女", pinyin: "nǚ", translation: "femme, fille" },
    { character: "忙", pinyin: "máng", translation: "occupé" },
    { character: "卖", pinyin: "mài", translation: "vendre" },
    { character: "高", pinyin: "gāo", translation: "haut, grand, élevé" },
    { character: "房间", pinyin: "fángjiān", translation: "chambre" },
];

